#!/bin/bash
set -ex
[ "$SERVICE_VERSION" ] || {
    echo "Sorry, but specifying a 'version:' option in dotcloud.yml is mandatory."
    exit 1
}
VERSION=$SERVICE_VERSION
echo "Requested PostgreSQL version: $VERSION."
CODEDIR=$PWD
BUILDDIR="$(dirname "$0")"
cp $BUILDDIR/run.postgres $HOME
mkdir -p $HOME/bin
cp $BUILDDIR/enslave $HOME/bin
[ -d $HOME/postgresql-$VERSION ] || {
	curl http://ftp.postgresql.org/pub/source/v$VERSION/postgresql-$VERSION.tar.gz | tar -zxf-
	cd postgresql-$VERSION
	./configure --prefix=$HOME/postgresql-$VERSION
	make install
    cd contrib
    make
    make install
}
rm -f $HOME/postgresql
ln -s postgresql-$VERSION $HOME/postgresql
[ -f $HOME/.ssh/id_rsa ] || {
	ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -N ''
	cat $HOME/.ssh/id_rsa.pub >> $HOME/.ssh/authorized_keys
}
cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys # FIXME
[ -f $HOME/password ] || {
	head -c8 /dev/random | base64 | tr -d = > $HOME/password
}
echo "User: $USER"
echo "Password: $(cat $HOME/password)"
